name: Deploy blog source to github pages

on: 
  push:
    branches:
      - server

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@master
      
    - name: build
      run: npm install && npm run pub

    - name: deploy
      uses: closertb/deploy-static-action@master
      with:
        type: 'server'
        name: 'doddle'
        cmd: 'npm run dev'
        targetPath: '../closertb.github.io'
        token: ${{ secrets.Deploy_Token }}
        requestUrl: 'http://deploy.closertb.site/operate/deploy'
        dist: 'dist'
        target: 'blog'